# Header

menu:
  主页: /
  随笔: /tags/随笔/
  相册: /photos/
  归档: /archives
# SubNav
subnav:
  github: "https://github.com/hanlinbei"
  weibo: "https://weibo.com/hanlinbei"
  rss: "atom.xml"
  zhihu: "https://www.zhihu.com/people/bei-ying-li-de-chen-mo"
  # qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/403896003"
  #acfun: "#"
  mail: "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=V2BiZWJgZWVmZxcmJnk0ODo"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:  

# Content

# 文章太长，截断按钮文字
#excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false 
 

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.jpg
# 微信二维码图片地址
weixin: /assets/img/wechatpay.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false 
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /themes/yilia/source/

#你的头像url
avatar: /assets/img/my.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
#gitment_owner: 'hanlinbei'      #你的 GitHub ID
#gitment_repo: 'https://github.com/hanlinbei/hanlinbei.github.io.git'          #存储评论的 repo
#gitment_oauth:
# client_id: '25575bc37dc6476b1777fe09bed07cc1e5cc396db1bf644cb1d15703568ed186'           #client ID
# client_secret: '403b5b81a02976488de008aab9e11048a46f8dd0df59bf1daf70527906ac104b'       #client secret
gitalk:
     enable: true #是否开启
     githubID: hanlinbei #你的Github用户名
     repo: hanlinbei.github.io #Github仓库名称
     ClientID: 34fe00e1256c48c428bd #创建的Application ClientID
     ClientSecret: c5be5e5725e9d8834030f4fea0cc2866e6b60763 #创建的Application ClientSecret
     adminUser: hanlinbei # 评论初始化账户(GitHub ID)
     distractionFreeMode: true # 是否开启分心自由模式 也就是免打扰

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: false
  aboutme: '关于我'

friends:
  友情链接1: http://localhost.4000/ 
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家 
# 网易云音乐插件
music:
  enable: true
  id: 442605338  # 网易云分享的ID
  autoplay: true  # 是否开启自动播放
# 是否开启访问量统计功能(不蒜子)
busuanzi:
  enable: true
aplayer:
  enable: true
# 版权声明
declare_type: 2 
licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/          # 当前应用的版权协议地址。
licensee_name: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'  # 版权协议的名称
licensee_img: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png      # 版权协议的Logo

